name: Lint Cache CI

runs:
  using: "composite"
  steps:
    - name: Restore lint cache
      uses: actions/cache@v3
      with:
        path: .cache/eslint/
        key: eslint-cache-${{ github.head_ref || github.ref_name }}