name: CI Front
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
      - 'packages/twenty-ui/**'
  pull_request: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  front-sb-build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
      NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch local actions
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Diagnostic disk space issue
        run: df -h
      - name: Front / Restore Storybook Task Cache
        uses: ./.github/workflows/actions/task-cache
        with:
          tag: scope:frontend
          tasks: storybook:build
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - name: Front / Build storybook
        run: npx nx storybook:build twenty-front
  front-sb-test-shipfox:
    runs-on: shipfox-8vcpu-ubuntu-2204
    timeout-minutes: 60
    needs: front-sb-build
    strategy:
      matrix:
        storybook_scope: [pages, modules]
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
      NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    steps:
      - name: Fetch local actions
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Install Playwright
        run: cd packages/twenty-front && npx playwright install
      - name: Front / Restore Storybook Task Cache
        uses: ./.github/workflows/actions/task-cache
        with:
          tag: scope:frontend
          tasks: storybook:build
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - name: Run storybook tests
        run: npx nx storybook:serve-and-test:static twenty-front --configuration=${{ matrix.storybook_scope }}