name: CI Front
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
      - 'packages/twenty-ui/**'
  pull_request:
    paths:
      - 'package.json'
      - 'packages/twenty-front/**'
      - 'packages/twenty-ui/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  front-pages-sb-test:
    runs-on: ci-8-cores
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
      STORYBOOK_SCOPE: pages
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch local actions
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Install Playwright
        run: cd packages/twenty-front && npx playwright install
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - name: Run storybook tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx nx run twenty-front:storybook:static:ci" \
            "npx wait-on tcp:6006 && npx nx run twenty-front:storybook:test"
  front-modules-sb-test:
    runs-on: ci-4-cores
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
      STORYBOOK_SCOPE: modules
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
            access_token: ${{ github.token }}
      - name: Fetch local actions
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Install Playwright
        run: cd packages/twenty-front && npx playwright install
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - name: Run storybook tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx nx run twenty-front:storybook:static:ci" \
            "npx wait-on tcp:6006 && npx nx run twenty-front:storybook:test"
  front-lint-tsc:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch local actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Restore lint cache
        uses: ./.github/workflows/actions/lint-cache
      - name: Restore typecheck cache
        uses: ./.github/workflows/actions/typecheck-cache
      - name: Front / Run linter & typecheck
        uses: ./.github/workflows/actions/nx-affected
        with:
          tag: scope:frontend
          target: lint typecheck
  front-jest:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch local actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Front / Run jest
        uses: ./.github/workflows/actions/nx-affected
        with:
          parallel: 1
          tag: scope:frontend
          target: test