name: CI Server
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-server/**'
      - 'packages/twenty-emails/**'
  pull_request:
    paths:
      - 'package.json'
      - 'packages/twenty-server/**'
      - 'packages/twenty-emails/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: twentycrm/twenty-postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - name: Fetch local actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Server / Run linter & typecheck
        uses: ./.github/workflows/actions/nx-affected
        with:
          tag: scope:backend
          tasks: lint,typecheck
      - name: Server / Run jest tests
        uses: ./.github/workflows/actions/nx-affected
        with:
          parallel: 1
          tag: scope:backend
          tasks: test
      - name: Server / Build
        run: npx nx build twenty-server
      - name: Server / Write .env
        run: npx nx reset:env twenty-server
      - name: Worker / Run
        run: MESSAGE_QUEUE_TYPE=sync npx nx worker twenty-server
