name: Assign

on:
  issues:
    types: [opened, edited]
  pull_request:
  issue_comment:
  pull_request_review_comment:

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.TOKEN_FOR_GITHUB_BOT }}
